language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.6
    - 7.0

branches:
    only:
        - master
        - /^\d+\.\d+$/

install:
    - phpenv config-rm xdebug.ini
    - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install

script:
    - vendor/bin/phpunit
